# Generated by Django 5.2.6 on 2025-09-18 19:00

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ok',
            field=models.URLField(blank=True, verbose_name='OK'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rutube',
            field=models.URLField(blank=True, verbose_name='Rutube'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vk',
            field=models.URLField(blank=True, verbose_name='VK'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vk_video',
            field=models.URLField(blank=True, verbose_name='VK видео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='Youtube'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='motto',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Девиз сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Краткое описание'),
        ),
    ]
