# Generated by Django 5.2.6 on 2025-10-05 14:56

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sitesettings_address_sitesettings_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Краткое описание для поисковых систем', max_length=255, verbose_name='SEO описание (description)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=200, verbose_name='SEO ключевые слова'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Если не указан, используется заголовок страницы', max_length=200, verbose_name='SEO заголовок (title)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='closure_message',
            field=models.TextField(blank=True, help_text='Сообщение, которое увидят пользователи при закрытии сайта', verbose_name='Сообщение при закрытии'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Основной контент'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 200x60 пикселей', upload_to='logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ok',
            field=models.URLField(blank=True, verbose_name='Одноклассники'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Основной телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Дополнительный телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vk',
            field=models.URLField(blank=True, verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vk_video',
            field=models.URLField(blank=True, verbose_name='VK Видео'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug', 'show_on_site'], name='main_page_slug_6ba70b_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['show_in_menu', 'show_on_site', 'order'], name='main_page_show_in_7ecb37_idx'),
        ),
    ]
