# Generated by Django 5.2.6 on 2025-12-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_managedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managedfile',
            options={'ordering': ['name'], 'verbose_name': 'Управляемый файл', 'verbose_name_plural': 'Управляемые файлы'},
        ),
        migrations.RemoveIndex(
            model_name='managedfile',
            name='main_manage_categor_164312_idx',
        ),
        migrations.RemoveIndex(
            model_name='managedfile',
            name='main_manage_file_pa_68d95a_idx',
        ),
        migrations.AddField(
            model_name='managedfile',
            name='file_permissions',
            field=models.CharField(blank=True, max_length=10, verbose_name='Права доступа'),
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='auto_backup',
            field=models.BooleanField(default=True, verbose_name='Авто-бэкап'),
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='category',
            field=models.CharField(choices=[('log', 'Лог-файлы'), ('config', 'Конфигурационные'), ('template', 'Шаблоны'), ('static', 'Статические'), ('media', 'Медиа'), ('database', 'Базы данных'), ('backup', 'Резервные копии'), ('other', 'Другие')], default='other', max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='encoding',
            field=models.CharField(default='utf-8', max_length=50, verbose_name='Кодировка'),
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='file_mtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='file_path',
            field=models.CharField(max_length=500, unique=True, verbose_name='Полный путь'),
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='Размер файла'),
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='is_text_file',
            field=models.BooleanField(default=True, verbose_name='Текстовый файл'),
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='max_backups',
            field=models.IntegerField(default=5, verbose_name='Макс. бэкапов'),
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='MIME тип'),
        ),
        migrations.AlterField(
            model_name='managedfile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя файла'),
        ),
    ]
