# Generated by Django 5.2.6 on 2025-09-27 21:34

import datetime
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_remove_portfoliocategory_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolioitem",
            name="image",
        ),
        migrations.AddField(
            model_name="portfoliocategory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now, verbose_name="Создан"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portfoliocategory",
            name="image",
            field=models.ImageField(
                default="portfolio/default-category.png",
                upload_to="portfolio/categories/",
                verbose_name="Изображение",
            ),
        ),
        migrations.AddField(
            model_name="portfoliocategory",
            name="seo_description",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="SEO описание"
            ),
        ),
        migrations.AddField(
            model_name="portfoliocategory",
            name="seo_keywords",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="SEO ключевые слова",
            ),
        ),
        migrations.AddField(
            model_name="portfoliocategory",
            name="seo_title",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="SEO заголовок"
            ),
        ),
        migrations.AddField(
            model_name="portfoliocategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="images",
            field=models.ImageField(
                default="portfolio/default.png",
                upload_to="portfolio/%Y/%m/%d/",
                verbose_name="Главное изображение",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="portfoliocategory",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliocategory",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Чем больше, тем выше", verbose_name="Порядок"
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="project_date",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                null=True,
                verbose_name="Дата проекта",
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="technologies",
            field=models.CharField(
                blank=True,
                help_text="Через запятую",
                max_length=300,
                verbose_name="Технологии",
            ),
        ),
    ]
