# Generated by Django 5.2.6 on 2025-12-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_review_portfolioreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
    ]
