# Generated by Django 5.2.6 on 2026-01-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_portfolioitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliocategory',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Переопределяет фоновое изображение для этой конкретной страницы', upload_to='hero_overrides/', verbose_name='Фон Hero'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='hero_is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть Hero-секцию на этой странице', verbose_name='Показывать Hero'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='hero_subtitle',
            field=models.TextField(blank=True, help_text='Если не заполнено, будет использовано краткое описание', verbose_name='Подзаголовок Hero'),
        ),
        migrations.AddField(
            model_name='portfoliocategory',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Если не заполнено, будет использовано стандартное название', max_length=255, verbose_name='Заголовок Hero'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Переопределяет фоновое изображение для этой конкретной страницы', upload_to='hero_overrides/', verbose_name='Фон Hero'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='hero_is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть Hero-секцию на этой странице', verbose_name='Показывать Hero'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='hero_subtitle',
            field=models.TextField(blank=True, help_text='Если не заполнено, будет использовано краткое описание', verbose_name='Подзаголовок Hero'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Если не заполнено, будет использовано стандартное название', max_length=255, verbose_name='Заголовок Hero'),
        ),
    ]
