# Generated by Django 5.2.6 on 2025-09-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
    ]
