# Generated by Django 5.2.6 on 2025-10-13 21:38

import accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 200x200 пикселей', null=True, upload_to=accounts.models.avatar_upload_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +7 XXX XXX-XX-XX', max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'created_at'], name='accounts_ti_status_9733dd_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', 'created_at'], name='accounts_ti_user_id_0d068a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketresponse',
            index=models.Index(fields=['ticket', 'created_at'], name='accounts_ti_ticket__b727d9_idx'),
        ),
    ]
