# Generated by Django 5.2.9 on 2026-01-15 19:54

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, upload_to='services/categories/', verbose_name='Изображение')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок')),
                ('seo_keywords', models.CharField(blank=True, max_length=200, verbose_name='SEO ключевые слова')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='SEO описание')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('short_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Краткое описание услуги')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание услуги')),
                ('icon', models.ImageField(blank=True, upload_to='services/icons/', verbose_name='Иконка услуги')),
                ('background', models.ImageField(blank=True, upload_to='services/backgrounds/', verbose_name='Фон услуги')),
                ('price_type', models.CharField(choices=[('fixed', 'Фиксированная цена'), ('from', 'От'), ('to', 'До'), ('range', 'От и до')], default='fixed', max_length=10, verbose_name='Тип цены')),
                ('price_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фиксированная цена')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена от')),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена до')),
                ('currency', models.CharField(choices=[('RUB', 'Рубли (₽)'), ('USD', 'Доллары ($)'), ('EUR', 'Евро (€)'), ('KZT', 'Тенге (₸)')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('can_order', models.BooleanField(default=True, help_text='Можно ли заказать эту услугу', verbose_name='Можно заказать')),
                ('is_displayed', models.BooleanField(default=True, help_text='Будет ли отображаться услуга на сайте', verbose_name='Отображается')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок')),
                ('seo_keywords', models.CharField(blank=True, max_length=200, verbose_name='SEO ключевые слова')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='SEO описание')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicecategory', verbose_name='Категория услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-created_at'],
            },
        ),
    ]
