# Generated by Django 5.2.6 on 2026-02-03 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_hero_image_service_hero_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Если больше 0, перекрывает скидку категории', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Индивидуальный процент скидки'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_on_sale',
            field=models.BooleanField(default=False, verbose_name='Акция активна'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='discount_active',
            field=models.BooleanField(default=False, verbose_name='Акция активна'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Скидка для всех услуг в этой категории, если у них нет своей', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки'),
        ),
    ]
