# Generated by Django 5.2.6 on 2026-06-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceorder_serviceorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_bg_color',
            field=models.CharField(blank=True, help_text="Цвет в формате HEX, RGB или HTML имя (например, #1f2937). Применяется для типа 'Однотонный цвет'", max_length=50, verbose_name='Цвет фона Hero'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_bg_gradient',
            field=models.CharField(blank=True, help_text="Кастомный CSS градиент (например, linear-gradient(135deg, #1e293b 0%, #0f172a 100%)). Применяется для типа 'Градиент'", max_length=255, verbose_name='Градиент фона Hero'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_bg_type',
            field=models.CharField(choices=[('global', 'Как на всем сайте'), ('image', 'Изображение'), ('gradient', 'Градиент'), ('cosmic', 'Космический mesh-градиент'), ('solid', 'Однотонный цвет')], default='global', help_text='Выберите тип заднего плана для Hero-секции этой страницы', max_length=20, verbose_name='Тип фона Hero'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_show_particles',
            field=models.CharField(choices=[('global', 'Как на всем сайте'), ('yes', 'Показывать'), ('no', 'Скрывать')], default='global', help_text='Показывать ли анимированные орбы и точечную сетку на заднем плане', max_length=10, verbose_name='Показывать сетку и блики'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='hero_bg_color',
            field=models.CharField(blank=True, help_text="Цвет в формате HEX, RGB или HTML имя (например, #1f2937). Применяется для типа 'Однотонный цвет'", max_length=50, verbose_name='Цвет фона Hero'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='hero_bg_gradient',
            field=models.CharField(blank=True, help_text="Кастомный CSS градиент (например, linear-gradient(135deg, #1e293b 0%, #0f172a 100%)). Применяется для типа 'Градиент'", max_length=255, verbose_name='Градиент фона Hero'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='hero_bg_type',
            field=models.CharField(choices=[('global', 'Как на всем сайте'), ('image', 'Изображение'), ('gradient', 'Градиент'), ('cosmic', 'Космический mesh-градиент'), ('solid', 'Однотонный цвет')], default='global', help_text='Выберите тип заднего плана для Hero-секции этой страницы', max_length=20, verbose_name='Тип фона Hero'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='hero_show_particles',
            field=models.CharField(choices=[('global', 'Как на всем сайте'), ('yes', 'Показывать'), ('no', 'Скрывать')], default='global', help_text='Показывать ли анимированные орбы и точечную сетку на заднем плане', max_length=10, verbose_name='Показывать сетку и блики'),
        ),
    ]
