# Generated by Django 5.2.6 on 2025-12-02 21:39

import django.db.models.deletion
import files.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название категории файлов', max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, help_text='Подробное описание назначения категории', verbose_name='Описание')),
                ('icon', models.CharField(blank=True, default='fa-file', help_text='CSS класс иконки (например: fa-file, fa-image)', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(blank=True, default='#007bff', help_text='Цвет в формате HEX (например: #007bff)', max_length=7, verbose_name='Цвет')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения категории в списке', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли категорию в интерфейсе', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория файлов',
                'verbose_name_plural': 'Категории файлов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Отображаемое название файла', max_length=255, verbose_name='Название')),
                ('original_name', models.CharField(help_text='Имя файла при загрузке', max_length=255, verbose_name='Оригинальное имя')),
                ('file', models.FileField(help_text='Загружаемый файл', upload_to=files.models.get_upload_path, verbose_name='Файл')),
                ('description', models.TextField(blank=True, help_text='Подробное описание содержимого файла', verbose_name='Описание')),
                ('tags', models.CharField(blank=True, help_text='Теги через запятую для поиска', max_length=500, verbose_name='Теги')),
                ('file_size', models.BigIntegerField(default=0, help_text='Размер файла в байтах', verbose_name='Размер файла')),
                ('mime_type', models.CharField(blank=True, help_text='MIME тип файла (например: image/jpeg, application/pdf)', max_length=100, verbose_name='MIME тип')),
                ('file_hash', models.CharField(blank=True, help_text='MD5 хеш файла для проверки целостности', max_length=32, verbose_name='MD5 хеш')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Сколько раз файл был скачан', verbose_name='Количество скачиваний')),
                ('is_public', models.BooleanField(default=False, help_text='Доступен ли файл для публичного просмотра', verbose_name='Публичный')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли файл в списке', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='Пользователь, загрузивший файл', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('category', models.ForeignKey(blank=True, help_text='Категория файла', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.filecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Номер версии файла', verbose_name='Номер версии')),
                ('version_file', models.FileField(help_text='Файл этой версии', upload_to='files/versions/', verbose_name='Файл версии')),
                ('comment', models.TextField(blank=True, help_text='Комментарий к этой версии', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, help_text='Пользователь, создавший версию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_versions', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('file', models.ForeignKey(help_text='Основной файл', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.file', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Версия файла',
                'verbose_name_plural': 'Версии файлов',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['category', 'is_active'], name='files_file_categor_56a7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='files_file_uploade_abf04e_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_hash'], name='files_file_file_ha_868749_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fileversion',
            unique_together={('file', 'version_number')},
        ),
    ]
