"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-gg&b-34chy82xwd424vn41_=i=nr$2mrxm5_-xj(ev6ed#h+_="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "*",
    "www.dpits-cms.ru",
    "dpits-cms.ru",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django_ckeditor_5",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_cleanup",
    "main.apps.MainConfig",
    "news.apps.NewsConfig",
    "portfolio.apps.PortfolioConfig",
    "reviews.apps.ReviewsConfig",
    "accounts.apps.AccountsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.site_settings",
                "main.context_processors.menu_items",
                "news.context_processors.latest_news",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "ru"
TIME_ZONE = "Europe/Moscow"
USE_I18N = True
USE_TZ = True
# Настройки аутентификации
LOGIN_REDIRECT_URL = "/accounts/profile/"
LOGIN_URL = "/accounts/login/"
LOGOUT_REDIRECT_URL = "/"
# Настройки аутентификации
LOGIN_REDIRECT_URL = "portfolio:client_dashboard"
LOGOUT_REDIRECT_URL = "portfolio:list"
LOGIN_URL = "accounts:login"
# Настройки сообщений
MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Jazzmin настройки для админ-панели Django
JAZZMIN_SETTINGS = {
    # === Основные настройки сайта ===
    "site_title": "Админ панель",
    "site_header": "Админ панель",
    "site_brand": "Админ панель",
    "welcome_sign": "Добро пожаловать в админ панель",
    # === Настройки логотипа и иконок ===
    "site_logo": "images/logo.png",
    "site_icon": "images/logo.png",
    "site_logo_classes": "img-circle",
    "site_brand_small_icon": "images/logo.png",
    "site_brand_small_text": "Админ",
    # === Функциональность ===
    "show_ui_builder": False,  # Отключить UI builder для продакшена
    # === Настройки меню ===
    "menu": [
        {"app": "main", "label": "Главная", "icon": "fas fa-home"},
        {"app": "news", "label": "Новости", "icon": "fas fa-newspaper"},
        {"app": "portfolio", "label": "Портфолио", "icon": "fas fa-briefcase"},
        {"app": "reviews", "label": "Отзывы", "icon": "fas fa-star"},
        {"app": "accounts", "label": "Аккаунты", "icon": "fas fa-users"},
    ],
    # === Настройки списков изменений ===
    "changelist": {
        "show_delete_link": True,
        "show_full_result_count": False,
    },
    # === Внешний вид и темы ===
    "ui": {
        "theme": "darkly",
        "dark_mode_theme": "darkly",
        "navbar_small_text": True,
        "footer_small_text": False,
        "body_small_text": True,
        "brand_small_text": True,
        "sidebar_nav_small_text": True,
    },
    # === Дополнительные улучшения (опционально) ===
    "search_model": ["auth.User", "main.Profile"],  # Модели для поиска в хедере
    "topmenu_links": [
        {"name": "На сайт", "url": "/", "new_tab": False},
        # {"name": "Контакты", "url": "/contacts/", "new_tab": False},
        # {"name": "О нас", "url": "/about/", "new_tab": False},
        # {"name": "FAQ", "url": "/faq/", "new_tab": False},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],  # Приложения для скрытия
    "hide_models": [],  # Модели для скрытия
    "order_with_respect_to": ["main", "news", "portfolio", "reviews", "accounts"],
}

# Альтернативный вариант с светлой темой
JAZZMIN_SETTINGS_LIGHT = {
    **JAZZMIN_SETTINGS,
    "ui": {
        "theme": "flatly",  # Светлая тема
        "dark_mode_theme": "darkly",
        "navbar_small_text": False,
        "footer_small_text": False,
        "body_small_text": False,
        "brand_small_text": False,
        "sidebar_nav_small_text": False,
    },
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": True,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": False,
}

# CKEditor 5 настройки
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
            "imageUpload",
            "mediaEmbed",
            "insertTable",
            "undo",
            "redo",
        ],
    },
    "extends": {
        "blockToolbar": [
            "paragraph",
            "heading1",
            "heading2",
            "heading3",
            "|",
            "bulletedList",
            "numberedList",
            "|",
            "blockQuote",
            "imageUpload",
        ],
        "toolbar": [
            "heading",
            "|",
            "outdent",
            "indent",
            "|",
            "bold",
            "italic",
            "link",
            "underline",
            "strikethrough",
            "code",
            "subscript",
            "superscript",
            "highlight",
            "|",
            "codeBlock",
            "sourceEditing",
            "insertImage",
            "bulletedList",
            "numberedList",
            "todoList",
            "|",
            "blockQuote",
            "imageUpload",
            "|",
            "fontSize",
            "fontFamily",
            "fontColor",
            "fontBackgroundColor",
            "mediaEmbed",
            "removeFormat",
            "insertTable",
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:alignLeft",
                "imageStyle:alignRight",
                "imageStyle:alignCenter",
                "imageStyle:side",
                "|",
            ],
            "styles": ["full", "side", "alignLeft", "alignRight", "alignCenter"],
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
                "tableProperties",
                "tableCellProperties",
            ],
            "tableProperties": {
                "borderColors": [
                    {"color": "#ccc"},
                    {"color": "#999"},
                    {"color": "#666"},
                    {"color": "#333"},
                    {"color": "#000"},
                ],
                "backgroundColors": [
                    {"color": "#fff"},
                    {"color": "#f8f9fa"},
                    {"color": "#e9ecef"},
                    {"color": "#dee2e6"},
                    {"color": "#ced4da"},
                ],
            },
        },
        "heading": {
            "options": [
                {
                    "model": "paragraph",
                    "title": "Paragraph",
                    "class": "ck-heading_paragraph",
                },
                {
                    "model": "heading1",
                    "view": "h1",
                    "title": "Heading 1",
                    "class": "ck-heading_heading1",
                },
                {
                    "model": "heading2",
                    "view": "h2",
                    "title": "Heading 2",
                    "class": "ck-heading_heading2",
                },
                {
                    "model": "heading3",
                    "view": "h3",
                    "title": "Heading 3",
                    "class": "ck-heading_heading3",
                },
            ]
        },
    },
    "list": {
        "properties": {
            "styles": "true",
            "startIndex": "true",
            "reversed": "true",
        }
    },
}

# Настройки кеширования (простая версия для разработки)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

# Настройки сессий (без Redis)
SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Настройки сессий
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
SESSION_COOKIE_AGE = 1209600  # 2 недели

CKEDITOR_5_ALLOW_ALL_TAGS = True
CKEDITOR_5_FILE_UPLOAD_PERMISSIONS = 0o644


# Email настройки (для уведомлений)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.yandex.ru"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "noreply@yourdomain.com"
EMAIL_HOST_PASSWORD = "your_password"
DEFAULT_FROM_EMAIL = "noreply@yourdomain.com"

# Логирование
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "debug.log"),
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "level": "INFO",
            "propagate": True,
        },
        "portfolio": {
            "handlers": ["file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
