# Generated by Django 5.2.6 on 2025-09-12 20:41

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('content', tinymce.models.HTMLField(verbose_name='Содержание')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('show_on_site', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок')),
                ('seo_keywords', models.CharField(blank=True, max_length=200, verbose_name='SEO ключевые слова')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='SEO описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(blank=True, max_length=20, verbose_name='Телефон 1')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='Телефон 2')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, upload_to='logos/', verbose_name='Логотип')),
                ('logo_text', models.CharField(blank=True, max_length=100, verbose_name='Текст логотипа')),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Слоган в шапке')),
                ('motto', models.CharField(blank=True, max_length=255, verbose_name='Девиз сайта')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('site_closed', models.BooleanField(default=False, verbose_name='Сайт закрыт')),
                ('closure_message', tinymce.models.HTMLField(blank=True, verbose_name='Сообщение при закрытии')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
