# Generated by Django 5.2.6 on 2025-09-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='closure_message',
            field=models.TextField(blank=True, verbose_name='Сообщение при закрытии'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
    ]
