# Generated by Django 5.2.6 on 2025-10-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_sitesettings_options_sitesettings_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.RemoveIndex(
            model_name='page',
            name='main_page_slug_6ba70b_idx',
        ),
        migrations.RemoveIndex(
            model_name='page',
            name='main_page_show_in_7ecb37_idx',
        ),
    ]
