# Generated by Django 5.2.6 on 2025-10-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Краткое описание для поисковых систем', max_length=255, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=200, verbose_name='SEO ключевые слова'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Если не указан, используется заголовок страницы', max_length=200, verbose_name='SEO заголовок (title)'),
        ),
    ]
