# Generated by Django 5.2.6 on 2025-12-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sitesettings_seo_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Отображаемое имя файла', max_length=255, verbose_name='Имя файла')),
                ('file_path', models.CharField(help_text='Абсолютный путь к файлу в файловой системе', max_length=500, unique=True, verbose_name='Полный путь к файлу')),
                ('category', models.CharField(choices=[('log', 'Лог-файлы'), ('config', 'Конфигурационные файлы'), ('template', 'Шаблоны'), ('static', 'Статические файлы'), ('media', 'Медиа файлы'), ('database', 'Базы данных'), ('backup', 'Резервные копии'), ('other', 'Другие файлы')], default='other', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, help_text='Краткое описание содержимого файла', verbose_name='Описание файла')),
                ('content', models.TextField(blank=True, help_text='Текстовое содержимое (только для текстовых файлов)', null=True, verbose_name='Содержимое файла')),
                ('is_text_file', models.BooleanField(default=True, help_text='Является ли файл текстовым (можно редактировать)', verbose_name='Текстовый файл')),
                ('encoding', models.CharField(default='utf-8', help_text='Кодировка файла', max_length=50, verbose_name='Кодировка')),
                ('is_active', models.BooleanField(default=True, help_text='Отслеживать ли изменения этого файла', verbose_name='Активен')),
                ('auto_backup', models.BooleanField(default=True, help_text='Создавать резервную копию перед редактированием', verbose_name='Авто-бэкап')),
                ('max_backups', models.PositiveIntegerField(default=5, help_text='Максимальное количество хранимых резервных копий', verbose_name='Макс. бэкапов')),
                ('file_size', models.BigIntegerField(default=0, editable=False, verbose_name='Размер файла (байт)')),
                ('file_mtime', models.DateTimeField(editable=False, null=True, verbose_name='Время изменения файла')),
                ('mime_type', models.CharField(default='', editable=False, max_length=100, verbose_name='MIME тип')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='Последняя проверка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
            ],
            options={
                'verbose_name': 'Управляемый файл',
                'verbose_name_plural': 'Управляемые файлы',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='main_manage_categor_164312_idx'), models.Index(fields=['file_path'], name='main_manage_file_pa_68d95a_idx')],
            },
        ),
    ]
