# Generated by Django 5.2.6 on 2025-12-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_managedfile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(help_text='Дата, за которую собрана статистика', unique=True, verbose_name='Дата логов')),
                ('total_lines', models.IntegerField(default=0, help_text='Общее количество строк в лог-файле', verbose_name='Всего строк')),
                ('error_count', models.IntegerField(default=0, help_text='Количество строк с ошибками', verbose_name='Ошибки')),
                ('warning_count', models.IntegerField(default=0, help_text='Количество строк с предупреждениями', verbose_name='Предупреждения')),
                ('info_count', models.IntegerField(default=0, help_text='Количество информационных строк', verbose_name='Информационные')),
                ('debug_count', models.IntegerField(default=0, help_text='Количество отладочных строк', verbose_name='Отладочные')),
                ('other_count', models.IntegerField(default=0, help_text='Количество строк других типов', verbose_name='Прочие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статистика логов',
                'verbose_name_plural': 'Статистика логов',
                'ordering': ['-log_date'],
            },
        ),
    ]
