# Generated by Django 5.2.6 on 2025-12-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_logstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название сайта'),
        ),
    ]
