# Generated by Django 5.2.6 on 2025-12-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_sitesettings_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Изображение для фонового баннера на главной странице', upload_to='hero_bg/', verbose_name='Фон Hero-секции'),
        ),
    ]
