# Generated by Django 5.2.6 on 2026-01-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_sitesettings_hero_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
            ],
            options={
                'verbose_name': 'Лог ошибок',
                'verbose_name_plural': 'Лог ошибок',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.logstats',),
        ),
    ]
