# Generated by Django 5.2.6 on 2026-01-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Яндекс.Метрика главный счетчик', max_length=200, verbose_name='Название баннера')),
                ('banner_type', models.CharField(choices=[('yandex_metrika', 'Яндекс.Метрика'), ('google_analytics', 'Google Analytics'), ('google_tag_manager', 'Google Tag Manager'), ('facebook_pixel', 'Facebook Pixel'), ('vk_retargeting', 'VK Ретаргетинг'), ('mailru_top', 'Mail.ru Top'), ('liveinternet', 'LiveInternet'), ('custom', 'Пользовательский код'), ('other', 'Другой')], default='yandex_metrika', max_length=50, verbose_name='Тип баннера')),
                ('code', models.TextField(help_text='HTML/JavaScript код для вставки на сайт', verbose_name='Код баннера')),
                ('position', models.CharField(choices=[('head', 'В <head> (рекомендуется для счетчиков)'), ('body_start', 'В начале <body>'), ('body_end', 'В конце <body> (рекомендуется для скриптов)'), ('header', 'В шапке сайта'), ('footer', 'В подвале сайта'), ('custom', 'Кастомная позиция (вручную в шаблоне)')], default='head', max_length=50, verbose_name='Позиция на странице')),
                ('is_active', models.BooleanField(default=True, help_text='Включить/выключить баннер', verbose_name='Активен')),
                ('show_on_all_pages', models.BooleanField(default=True, help_text='Если включено, баннер будет отображаться на всех страницах сайта', verbose_name='Показывать на всех страницах')),
                ('show_on_index', models.BooleanField(default=True, verbose_name='Показывать на главной')),
                ('show_on_pages', models.BooleanField(default=True, verbose_name='Показывать на страницах')),
                ('show_on_news', models.BooleanField(default=True, verbose_name='Показывать на новостях')),
                ('show_on_portfolio', models.BooleanField(default=True, verbose_name='Показывать на портфолио')),
                ('enabled_for_admin', models.BooleanField(default=False, help_text='Если включено, баннер будет виден администраторам сайта', verbose_name='Показывать администраторам')),
                ('enabled_for_staff', models.BooleanField(default=False, help_text='Если включено, баннер будет виден персоналу сайта', verbose_name='Показывать персоналу')),
                ('enabled_for_users', models.BooleanField(default=True, help_text='Если включено, баннер будет виден обычным пользователям', verbose_name='Показывать пользователям')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше баннер в списке', verbose_name='Порядок отображения')),
                ('counter_id', models.CharField(blank=True, help_text='ID счетчика Яндекс.Метрики, Google Analytics и т.д.', max_length=100, verbose_name='ID счетчика')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о баннере', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Статистический баннер',
                'verbose_name_plural': 'Статистические баннеры',
                'ordering': ['order', 'name'],
            },
        ),
    ]
