# Generated by Django 5.2.6 on 2026-01-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_statisticsbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, help_text='Если не заполнено, будет использовано стандартное название', max_length=255, verbose_name='Заголовок Hero')),
                ('hero_subtitle', models.TextField(blank=True, help_text='Если не заполнено, будет использовано краткое описание', verbose_name='Подзаголовок Hero')),
                ('hero_image', models.ImageField(blank=True, help_text='Переопределяет фоновое изображение для этой конкретной страницы', upload_to='hero_overrides/', verbose_name='Фон Hero')),
                ('hero_is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть Hero-секцию на этой странице', verbose_name='Показывать Hero')),
                ('app_name', models.CharField(choices=[('news', 'Новости (общий список)'), ('portfolio', 'Портфолио (общий список)'), ('services', 'Услуги (общий список)'), ('reviews', 'Отзывы'), ('contacts', 'Контакты'), ('home', 'Главная страница')], max_length=50, unique=True, verbose_name='Раздел сайта')),
            ],
            options={
                'verbose_name': 'Hero раздел',
                'verbose_name_plural': 'Hero разделы',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Переопределяет фоновое изображение для этой конкретной страницы', upload_to='hero_overrides/', verbose_name='Фон Hero'),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть Hero-секцию на этой странице', verbose_name='Показывать Hero'),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_subtitle',
            field=models.TextField(blank=True, help_text='Если не заполнено, будет использовано краткое описание', verbose_name='Подзаголовок Hero'),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Если не заполнено, будет использовано стандартное название', max_length=255, verbose_name='Заголовок Hero'),
        ),
    ]
