# Generated by Django 5.2.9 on 2026-01-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_appherosettings_page_hero_image_page_hero_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appherosettings',
            name='app_name',
            field=models.CharField(choices=[('news', 'Новости (общий список)'), ('portfolio', 'Портфолио (общий список)'), ('services', 'Услуги (общий список)'), ('reviews', 'Отзывы'), ('contacts', 'Контакты'), ('about', 'О нас'), ('profile', 'Профиль'), ('home', 'Главная страница')], max_length=50, unique=True, verbose_name='Раздел сайта'),
        ),
    ]
