# Generated by Django 5.2.6 on 2026-02-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_appherosettings_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='icon_facebook',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети Facebook', upload_to='icons/social/', verbose_name='Иконка Facebook'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_instagram',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети Instagram', upload_to='icons/social/', verbose_name='Иконка Instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_ok',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети Одноклассники', upload_to='icons/social/', verbose_name='Иконка Одноклассники'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_rutube',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети Rutube', upload_to='icons/social/', verbose_name='Иконка Rutube'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_telegram',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети Telegram', upload_to='icons/social/', verbose_name='Иконка Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_vk',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети ВКонтакте', upload_to='icons/social/', verbose_name='Иконка ВКонтакте'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_vk_video',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети VK Видео', upload_to='icons/social/', verbose_name='Иконка VK Видео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_youtube',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети YouTube', upload_to='icons/social/', verbose_name='Иконка YouTube'),
        ),
    ]
