# Generated by Django 5.2.6 on 2026-02-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_appherosettings_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание (для списка)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Иконка сайта (32x32 или 64x64)', upload_to='logos/', verbose_name='Фавикон'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Переопределяет фоновое изображение для этой конкретной страницы', upload_to='hero_overrides/', verbose_name='Фон Hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть Hero-секцию на этой странице', verbose_name='Показывать Hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, help_text='Если не заполнено, будет использовано краткое описание', verbose_name='Подзаголовок Hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Если не заполнено, будет использовано стандартное название', max_length=255, verbose_name='Заголовок Hero'),
        ),
    ]
