# Generated by Django 5.2.6 on 2026-02-08 08:59

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_sitesettings_icon_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pinterest',
            field=models.URLField(blank=True, verbose_name='Pinterest'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='skype',
            field=models.CharField(blank=True, help_text='Логин или ссылка', max_length=100, verbose_name='Skype'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='threads',
            field=models.URLField(blank=True, verbose_name='Threads'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter (X)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='viber',
            field=models.CharField(blank=True, help_text='Номер телефона или ссылка', max_length=100, verbose_name='Viber'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Номер телефона или ссылка', max_length=100, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Изображение для фонового баннера на главной странице', upload_to=main.models.upload_to_hero_bg, verbose_name='Фон Hero-секции'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_facebook',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети Facebook', upload_to=main.models.upload_to_facebook_icon, verbose_name='Иконка Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_instagram',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети Instagram', upload_to=main.models.upload_to_instagram_icon, verbose_name='Иконка Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_ok',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети Одноклассники', upload_to=main.models.upload_to_ok_icon, verbose_name='Иконка Одноклассники'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_rutube',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети Rutube', upload_to=main.models.upload_to_rutube_icon, verbose_name='Иконка Rutube'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_telegram',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети Telegram', upload_to=main.models.upload_to_telegram_icon, verbose_name='Иконка Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_vk',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети ВКонтакте', upload_to=main.models.upload_to_vk_icon, verbose_name='Иконка ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_vk_video',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети VK Видео', upload_to=main.models.upload_to_vk_video_icon, verbose_name='Иконка VK Видео'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='icon_youtube',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети YouTube', upload_to=main.models.upload_to_youtube_icon, verbose_name='Иконка YouTube'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 200x60 пикселей', upload_to=main.models.upload_to_logos, verbose_name='Логотип'),
        ),
    ]
