# Generated by Django 5.2.6 on 2026-02-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_sitesettings_description_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_icon',
            field=models.ImageField(blank=True, upload_to='social_icons/', verbose_name='Иконка Facebook'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_icon',
            field=models.ImageField(blank=True, upload_to='social_icons/', verbose_name='Иконка Instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ok_icon',
            field=models.ImageField(blank=True, upload_to='social_icons/', verbose_name='Иконка Одноклассники'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='rutube_icon',
            field=models.ImageField(blank=True, upload_to='social_icons/', verbose_name='Иконка Rutube'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_icon',
            field=models.ImageField(blank=True, upload_to='social_icons/', verbose_name='Иконка Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vk_icon',
            field=models.ImageField(blank=True, upload_to='social_icons/', verbose_name='Иконка ВКонтакте'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vk_video_icon',
            field=models.ImageField(blank=True, upload_to='social_icons/', verbose_name='Иконка VK Видео'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_icon',
            field=models.ImageField(blank=True, upload_to='social_icons/', verbose_name='Иконка YouTube'),
        ),
    ]
