# Generated by Django 5.2.6 on 2026-02-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_sitesettings_facebook_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_icon',
            field=models.ImageField(blank=True, upload_to='social_icons/', verbose_name='Иконка LinkedIn'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pinterest',
            field=models.URLField(blank=True, verbose_name='Pinterest'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pinterest_icon',
            field=models.ImageField(blank=True, upload_to='social_icons/', verbose_name='Иконка Pinterest'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_icon',
            field=models.ImageField(blank=True, upload_to='social_icons/', verbose_name='Иконка Twitter'),
        ),
    ]
