# Generated by Django 5.2.6 on 2026-02-08 09:05

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_sitesettings_linkedin_sitesettings_pinterest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='icon_linkedin',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети LinkedIn', upload_to=main.models.upload_to_linkedin_icon, verbose_name='Иконка LinkedIn'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_pinterest',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети Pinterest', upload_to=main.models.upload_to_pinterest_icon, verbose_name='Иконка Pinterest'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_skype',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети Skype', upload_to=main.models.upload_to_skype_icon, verbose_name='Иконка Skype'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_threads',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети Threads', upload_to=main.models.upload_to_threads_icon, verbose_name='Иконка Threads'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_twitter',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети Twitter (X)', upload_to=main.models.upload_to_twitter_icon, verbose_name='Иконка Twitter (X)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_viber',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети Viber', upload_to=main.models.upload_to_viber_icon, verbose_name='Иконка Viber'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='icon_whatsapp',
            field=models.ImageField(blank=True, help_text='Иконка для соцсети WhatsApp', upload_to=main.models.upload_to_whatsapp_icon, verbose_name='Иконка WhatsApp'),
        ),
    ]
