# Generated by Django 5.2.6 on 2026-02-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_sitesettings_icon_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='', help_text='Название компании для отображения в заголовках страниц', max_length=100, verbose_name='Название компании'),
        ),
    ]
