# Generated by Django 5.2.6 on 2026-02-03 08:35

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_sitesettings_linkedin_sitesettings_linkedin_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contacts',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст в разделе контактов'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
