# Generated by Django 5.2.6 on 2026-04-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_sitesettings_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='domain',
            field=models.CharField(blank=True, default='dpits-cms.ru', max_length=100, verbose_name='Домен'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='slogan_domain',
            field=models.CharField(blank=True, default='Разработка сайтов и веб-приложений', max_length=255, verbose_name='Слоган домена'),
        ),
    ]
