# Generated by Django 5.2.6 on 2026-04-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='slug',
            field=models.SlugField(default=' ', max_length=200, unique=True, verbose_name='URL-адрес'),
            preserve_default=False,
        ),
    ]
