# Generated by Django 5.2.6 on 2026-05-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_paymentmethod_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='menu_icon',
            field=models.CharField(blank=True, default='', help_text='Например: fas fa-home. Отображается в навигационном меню рядом с названием страницы', max_length=80, verbose_name='Иконка меню (FA класс)'),
        ),
        migrations.AddField(
            model_name='page',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Счётчик просмотров страницы', verbose_name='Просмотры'),
        ),
    ]
