# Generated by Django 5.2.6 on 2026-05-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_page_views_menu_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя отправителя', max_length=100, verbose_name='Имя')),
                ('contact', models.CharField(help_text='Контактные данные отправителя', max_length=150, verbose_name='Email / Телефон')),
                ('message', models.TextField(help_text='Текст сообщения', verbose_name='Сообщение')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP-адрес отправителя (заполняется автоматически)', null=True, verbose_name='IP-адрес')),
                ('is_read', models.BooleanField(default=False, help_text='Отметьте, когда ознакомитесь с сообщением', verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Сообщения обратной связи',
                'ordering': ['-created_at'],
            },
        ),
    ]
