# Generated by Django 5.2.6 on 2026-06-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_add_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appherosettings',
            name='hero_bg_color',
            field=models.CharField(blank=True, help_text="Цвет в формате HEX, RGB или HTML имя (например, #1f2937). Применяется для типа 'Однотонный цвет'", max_length=50, verbose_name='Цвет фона Hero'),
        ),
        migrations.AddField(
            model_name='appherosettings',
            name='hero_bg_gradient',
            field=models.CharField(blank=True, help_text="Кастомный CSS градиент (например, linear-gradient(135deg, #1e293b 0%, #0f172a 100%)). Применяется для типа 'Градиент'", max_length=255, verbose_name='Градиент фона Hero'),
        ),
        migrations.AddField(
            model_name='appherosettings',
            name='hero_bg_type',
            field=models.CharField(choices=[('global', 'Как на всем сайте'), ('image', 'Изображение'), ('gradient', 'Градиент'), ('cosmic', 'Космический mesh-градиент'), ('solid', 'Однотонный цвет')], default='global', help_text='Выберите тип заднего плана для Hero-секции этой страницы', max_length=20, verbose_name='Тип фона Hero'),
        ),
        migrations.AddField(
            model_name='appherosettings',
            name='hero_show_particles',
            field=models.CharField(choices=[('global', 'Как на всем сайте'), ('yes', 'Показывать'), ('no', 'Скрывать')], default='global', help_text='Показывать ли анимированные орбы и точечную сетку на заднем плане', max_length=10, verbose_name='Показывать сетку и блики'),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_bg_color',
            field=models.CharField(blank=True, help_text="Цвет в формате HEX, RGB или HTML имя (например, #1f2937). Применяется для типа 'Однотонный цвет'", max_length=50, verbose_name='Цвет фона Hero'),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_bg_gradient',
            field=models.CharField(blank=True, help_text="Кастомный CSS градиент (например, linear-gradient(135deg, #1e293b 0%, #0f172a 100%)). Применяется для типа 'Градиент'", max_length=255, verbose_name='Градиент фона Hero'),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_bg_type',
            field=models.CharField(choices=[('global', 'Как на всем сайте'), ('image', 'Изображение'), ('gradient', 'Градиент'), ('cosmic', 'Космический mesh-градиент'), ('solid', 'Однотонный цвет')], default='global', help_text='Выберите тип заднего плана для Hero-секции этой страницы', max_length=20, verbose_name='Тип фона Hero'),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_show_particles',
            field=models.CharField(choices=[('global', 'Как на всем сайте'), ('yes', 'Показывать'), ('no', 'Скрывать')], default='global', help_text='Показывать ли анимированные орбы и точечную сетку на заднем плане', max_length=10, verbose_name='Показывать сетку и блики'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bg_color',
            field=models.CharField(default='#0e1430', help_text="Цвет по умолчанию (например, #0e1430). Используется при типе 'Однотонный цвет'", max_length=50, verbose_name='Глобальный цвет фона Hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bg_gradient',
            field=models.CharField(default='linear-gradient(135deg, #6366f1 0%, #1e3c72 100%)', help_text="Кастомный CSS градиент по умолчанию. Используется при типе 'Градиент'", max_length=255, verbose_name='Глобальный градиент фона Hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bg_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('gradient', 'Градиент'), ('cosmic', 'Космический mesh-градиент'), ('solid', 'Однотонный цвет')], default='image', help_text='Выберите тип заднего плана по умолчанию для Hero-секции', max_length=20, verbose_name='Глобальный тип фона Hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_blur_amount',
            field=models.PositiveIntegerField(default=4, help_text='Размытие заднего фона в пикселях (0 - выключить)', verbose_name='Сила размытия Hero фона'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_overlay_opacity',
            field=models.FloatField(default=0.85, help_text='Прозрачность затемняющего слоя поверх фона (от 0.0 до 1.0)', verbose_name='Прозрачность затемнения Hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_show_particles',
            field=models.BooleanField(default=True, help_text='Показывать ли по умолчанию декоративные блики и точечную сетку', verbose_name='Глобально показывать сетку и блики'),
        ),
    ]
