# Generated by Django 5.2.6 on 2025-12-16 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Краткое описание вашего вопроса или сообщения', max_length=200, verbose_name='Тема')),
                ('message', models.TextField(help_text='Подробно опишите ваш вопрос или предложение', verbose_name='Сообщение')),
                ('email', models.EmailField(help_text='На этот адрес будет отправлен ответ', max_length=254, verbose_name='Email для ответа')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('read', 'Прочитано'), ('replied', 'Отвечено'), ('archived', 'Архивировано')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_notes', models.TextField(blank=True, help_text='Внутренние заметки для администраторов', verbose_name='Заметки администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('email_sent', models.BooleanField(default=False, help_text='Было ли отправлено уведомление на почту', verbose_name='Email отправлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение обратной связи',
                'verbose_name_plural': 'Сообщения обратной связи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='feedback_fe_status_0f5aa3_idx'), models.Index(fields=['user', 'created_at'], name='feedback_fe_user_id_0818e6_idx')],
            },
        ),
    ]
