# Generated by Django 5.2.6 on 2025-12-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сообщение обратной связи', 'verbose_name_plural': 'Обратная связь'},
        ),
    ]
