# Generated by Django 5.2.6 on 2025-09-16 16:32

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newscategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Краткое описание'),
        ),
    ]
