# Generated by Django 5.2.6 on 2025-11-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO ключевые слова'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок'),
        ),
    ]
