# Generated by Django 5.2.6 on 2025-11-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newscategory_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news/default-category.png', upload_to='news/', verbose_name='Изображение'),
        ),
    ]
