# Generated by Django 5.2.6 on 2025-12-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
