# Generated by Django 5.2.6 on 2026-04-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_newstag_news_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='news/default-category.png', help_text='Оставьте стандартное изображение, чтобы использовать картинку из категории', upload_to='news/', verbose_name='Изображение'),
        ),
    ]
