# Generated by Django 5.2.9 on 2026-04-27 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Новость будет видна на сайте только после наступления этой даты.', verbose_name='Дата публикации'),
        ),
    ]
