# Generated by Django 5.2.6 on 2025-10-05 10:38

import django_ckeditor_5.fields
import portfolio.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_portfolioitem_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliocategory',
            options={'ordering': ['-order', 'name'], 'verbose_name': 'Категория портфолио', 'verbose_name_plural': 'Категории портфолио'},
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='images',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(default='portfolio/default-category.png', upload_to=portfolio.utils.custom_upload_to, verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO ключевые слова'),
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='requirements_file',
            field=models.FileField(blank=True, upload_to=portfolio.utils.custom_upload_to, verbose_name='Файл требований'),
        ),
        migrations.AlterField(
            model_name='ordermessage',
            name='file',
            field=models.FileField(blank=True, upload_to=portfolio.utils.custom_upload_to, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='portfoliocategory',
            name='image',
            field=models.ImageField(default='portfolio/default-category.png', upload_to=portfolio.utils.custom_upload_to, verbose_name='Изображение'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('client', 'portfolio_item')},
        ),
    ]
