# Generated by Django 5.2.6 on 2025-10-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfoliocategory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='PortfolioReview',
        ),
        migrations.AlterModelOptions(
            name='portfolioreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв о работе', 'verbose_name_plural': 'Отзывы о работах'},
        ),
    ]
